---
name: CI_Lighthouse
on: [push]
jobs:
  lhci:
    name: Lighthouse Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code     
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: npm install   
        run:  npm install
      - name: Check Build Token
        run: echo ${{ secrets.BUILD_TOKEN_EDWARD }}  
      - name: run Lighthouse CI
        continue-on-error: true
        run: |
          npm install -g @lhci/cli
          lhci autorun --collect.url=https://tplanet.townway.com.tw
      - name: Generate Lighthouse report
        continue-on-error: true
        run: lhci upload --target=lhci --serverBaseUrl=http://111.251.181.239:9001/ --token=${{ secrets.BUILD_TOKEN_EDWARD }}      
      - name: Upload Lighthouse report
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with: 
          name: lighthouse-report
          path: ./lighthouse-report
      - name: Send Slack Notification
        continue-on-error: true
        uses: rtCamp/action-slack-notify@v2
        with:
          entryPoint: '{"text": text: "Git push notification: A new push has been made to the repository."}'      
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
...
