---
name: CI_Lighthouse
on: [push]
jobs:
  lhci:
    name: Lighthouse Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code     
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: npm install   
        run:  npm install
      - name: Check Admin Token
        run: echo ${{ secrets.BUILD_TOKEN_EDWARD }}  
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli
          lhci autorun --collect.url=https://tplanet.townway.com.tw
      - name: Generate Lighthouse report
        if: ${{ always() }}
        run: lhci upload --target=lhci --serverBaseUrl=http://111.251.181.239:9001/ --token=${{ secrets.BUILD_TOKEN_EDWARD }}      
      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v2
        with: 
          name: lighthouse-report
          path: ./lighthouse-report
      - name: Send Slack Notification
        uses: slack/github-action@v3
        with:
          status: ${{ job.status }}
          text: "測試通知：Lighthouse CI測試結果：${{ job.status }}"
          author_name: "Lighthouse CI"
          title: "Lighthouse CI測試結果"
          title_url: ${{ env.CI_JOB_URL }}
          color: ${{ job.status == 'success' && 'good' || job.status == 'failure' && 'danger' || 'warning' }}
        env:
          CI_JOB_URL: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
...    
