---
name: Test Website Availability

on: 
  push:

jobs: 
  test-website:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Test Website Availability
      run: |
        curl -I https://tplanet.townway.com.tw
...  
