---
- name: Ping Website

  on: 
    push:

  jobs: 
    ping:
      runs-on: ubuntu-latest

      steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Ping website
        run: ping https://tplanet.townway.com.tw
...  
